Openchallenge ja cli
code-check/challenge-helloworld pull request #3
Opened 2017-06-15 07:49 UTC by TsubasaK111

@takayukioda review me!

2017-06-15 08:41 UTC, takayukioda requested changes

2017-06-15 08:41 UTC, takayukioda commented on README.md
> +画面上部に、制限時間・或いは解答締切が表示されるようになります。
> 或いは

ひらがなでおねがい

2017-06-15 08:41 UTC, takayukioda commented on README.md
> +### 2-3. ファイルの編集
where is `2-2` ?

2017-06-15 08:41 UTC, takayukioda commented on README.md
>  保存が完了したら"continue"ボタンを選択しましょう。
`編集を続ける` ボタンで！

2017-06-15 08:41 UTC, takayukioda commented on README.md
>  エディタ中部の”RUN”ボタンをクリックしてみましょう。
`テスト実行` ボタンに変わってます！

2017-06-20 03:39 UTC, TsubasaK111 commented on README.md
> +画面上部に、制限時間・或いは解答締切が表示されるようになります。
👍

2017-06-20 03:40 UTC, TsubasaK111 commented on README.md
> +### 2-3. ファイルの編集
👍

2017-06-20 03:40 UTC, TsubasaK111 commented on README.md
>  保存が完了したら"continue"ボタンを選択しましょう。
👍

2017-06-20 03:40 UTC, TsubasaK111 commented on README.md
>  エディタ中部の”RUN”ボタンをクリックしてみましょう。
👍

2017-06-20 03:43 UTC, TsubasaK111 commented
@takayukioda review me again!

2017-06-20 03:45 UTC, takayukioda approved these changes
![LGTM](http://i.giphy.com/xUPGcmF2iGsTGEFVL2.gif)

2017-06-20 03:45 UTC, merged